private static readonly IReadOnlyDictionary<string, string> TraditionalChineseLocalization =
    new Dictionary<string, string>
    {
        // ---- Dashboard ----
        [nameof(SunsetLabel)] = "日落",
        [nameof(SunriseLabel)] = "日出",
        [nameof(SunsetTransitionTooltip)] = "日落過渡",
        [nameof(SunriseTransitionTooltip)] = "日出過渡",
        [nameof(OffsetTooltipHeader)] = "偏移量",
        [nameof(TemperatureOffsetLabel)] = "色溫偏移",
        [nameof(BrightnessOffsetLabel)] = "亮度偏移",
        [nameof(ClickToResetLabel)] = "點擊以重設",
        [nameof(OffsetLabel)] = "偏移",

        // ---- Main window ----
        [nameof(ToggleLightBulbTooltip)] = "切換 LightBulb",
        [nameof(HideToTrayTooltip)] = "隱藏至系統匣",
        [nameof(PreviewText)] = "預覽",
        [nameof(StopPreviewTooltip)] = "停止預覽",
        [nameof(StartPreviewTooltip)] = "開始預覽",
        [nameof(SettingsText)] = "設定",
        [nameof(OpenSettingsTooltip)] = "開啟設定",

        // ---- Settings dialog ----
        [nameof(ResetButton)] = "重設",
        [nameof(ResetTooltip)] = "重設為預設值",
        [nameof(CancelButton)] = "取消",
        [nameof(SaveButton)] = "儲存",

        // ---- Settings tabs ----
        [nameof(GeneralTabName)] = "一般",
        [nameof(LocationTabName)] = "位置",
        [nameof(AdvancedTabName)] = "進階",
        [nameof(AppWhitelistTabName)] = "應用程式白名單",
        [nameof(HotkeysTabName)] = "快捷鍵",

        // ---- Advanced settings tab ----
        [nameof(ThemeLabel)] = "主題",
        [nameof(ThemeTooltip)] = "介面的顯示主題",
        [nameof(LanguageLabel)] = "語言",
        [nameof(LanguageTooltip)] = "介面的顯示語言",
        [nameof(StartWithWindowsLabel)] = "隨 Windows 啟動",
        [nameof(StartWithWindowsTooltip)] = "在登入時自動啟動 LightBulb",
        [nameof(AutoUpdateLabel)] = "自動更新",
        [nameof(AutoUpdateTooltip)] = "自動下載並安裝更新",
        [nameof(DefaultToDayConfigLabel)] = "預設為日間設定",
        [nameof(DefaultToDayConfigTooltip)] = "在無法判斷目前時段時，套用日間設定",
        [nameof(PauseWhenFullscreenLabel)] = "全螢幕時暫停",
        [nameof(PauseWhenFullscreenTooltip)] = "當應用程式以全螢幕執行時暫停 LightBulb",
        [nameof(GammaSmoothingLabel)] = "色彩平滑過渡",
        [nameof(GammaSmoothingTooltip)] = "在更新色彩時啟用平滑過渡效果",
        [nameof(GammaPollingLabel)] = "色彩輪詢",
        [nameof(GammaPollingTooltip)] = "定期重新套用色彩設定以防止被覆寫",

        // ---- General settings tab ----
        [nameof(DayTemperatureLabel)] = "日間色溫",
        [nameof(DayTemperatureTooltip)] = "日間的螢幕色溫",
        [nameof(NightTemperatureLabel)] = "夜間色溫",
        [nameof(NightTemperatureTooltip)] = "夜間的螢幕色溫",
        [nameof(DayBrightnessLabel)] = "日間亮度",
        [nameof(DayBrightnessTooltip)] = "日間的螢幕亮度",
        [nameof(NightBrightnessLabel)] = "夜間亮度",
        [nameof(NightBrightnessTooltip)] = "夜間的螢幕亮度",
        [nameof(TransitionDurationLabel)] = "過渡時長",
        [nameof(TransitionDurationTooltip)] = "從日間設定過渡到夜間設定所需的時間",
        [nameof(TransitionOffsetLabel)] = "過渡偏移",
        [nameof(TransitionOffsetTooltip)] = "日出與日落過渡的時間偏移量",

        // ---- Location settings tab ----
        [nameof(SolarConfigLabel)] = "日照設定",
        [nameof(ManualLabel)] = "手動",
        [nameof(ManualTooltip)] = "手動設定日出與日落時間",
        [nameof(LocationBasedLabel)] = "依位置",
        [nameof(LocationBasedTooltip)] = "根據目前位置自動判斷日出與日落時間",
        [nameof(SunriseTimeLabel)] = "日出時間",
        [nameof(SunsetTimeLabel)] = "日落時間",
        [nameof(YourLocationLabel)] = "您的位置",
        [nameof(AutoDetectLocationTooltip)] = "自動偵測位置",
        [nameof(LocationQueryTooltip)] = "搜尋位置",
        [nameof(SetLocationTooltip)] = "設定位置",
        [nameof(LocationErrorText)] = "無法取得位置資訊",

        // ---- Hot key settings tab ----
        [nameof(ToggleLightBulbHotkeyLabel)] = "切換 LightBulb",
        [nameof(ToggleLightBulbHotkeyTooltip)] = "啟用或停用 LightBulb 的快捷鍵",
        [nameof(ToggleWindowLabel)] = "切換視窗",
        [nameof(ToggleWindowHotkeyTooltip)] = "顯示或隱藏主視窗的快捷鍵",
        [nameof(IncreaseTemperatureOffsetLabel)] = "提高色溫偏移",
        [nameof(IncreaseTemperatureOffsetTooltip)] = "提高色溫偏移量的快捷鍵",
        [nameof(DecreaseTemperatureOffsetLabel)] = "降低色溫偏移",
        [nameof(DecreaseTemperatureOffsetTooltip)] = "降低色溫偏移量的快捷鍵",
        [nameof(IncreaseBrightnessOffsetLabel)] = "提高亮度偏移",
        [nameof(IncreaseBrightnessOffsetTooltip)] = "提高亮度偏移量的快捷鍵",
        [nameof(DecreaseBrightnessOffsetLabel)] = "降低亮度偏移",
        [nameof(DecreaseBrightnessOffsetTooltip)] = "降低亮度偏移量的快捷鍵",
        [nameof(ResetOffsetLabel)] = "重設偏移",
        [nameof(ResetOffsetHotkeyTooltip)] = "將所有偏移量重設為零的快捷鍵",

        // ---- Application whitelist settings tab ----
        [nameof(AppWhitelistLabel)] = "應用程式白名單",
        [nameof(RefreshAppsTooltip)] = "重新整理應用程式清單",
        [nameof(PauseForWhitelistedTooltip)] = "對白名單內的應用程式暫停 LightBulb",

        // ---- Tray icon context menu ----
        [nameof(TrayShowMenuItem)] = "顯示",
        [nameof(TrayHideMenuItem)] = "隱藏",
        [nameof(TraySettingsMenuItem)] = "設定",
        [nameof(TrayEnableMenuItem)] = "啟用",
        [nameof(TrayDisableOnlyMenuItem)] = "停用",
        [nameof(TrayDisableMenuItem)] = "停用",
        [nameof(TrayDisableUntilSunriseMenuItem)] = "停用至日出",
        [nameof(TrayDisableFor1DayMenuItem)] = "停用 1 天",
        [nameof(TrayDisableFor12HoursMenuItem)] = "停用 12 小時",
        [nameof(TrayDisableFor6HoursMenuItem)] = "停用 6 小時",
        [nameof(TrayDisableFor3HoursMenuItem)] = "停用 3 小時",
        [nameof(TrayDisableFor1HourMenuItem)] = "停用 1 小時",
        [nameof(TrayDisableFor30MinutesMenuItem)] = "停用 30 分鐘",
        [nameof(TrayDisableFor15MinutesMenuItem)] = "停用 15 分鐘",
        [nameof(TrayDisableFor5MinutesMenuItem)] = "停用 5 分鐘",
        [nameof(TrayDisableFor1MinuteMenuItem)] = "停用 1 分鐘",
        [nameof(TrayExitMenuItem)] = "結束",

        [nameof(TrayTooltipDisabled)] = "LightBulb（已停用）",

        // ---- Dialog messages ----
        [nameof(UpdateAvailableTitle)] = "有可用的更新",
        [nameof(UpdateAvailableMessage)] = "有新版本的 LightBulb 可供下載。",
        [nameof(InstallButton)] = "安裝",
        [nameof(CloseButton)] = "關閉",
        [nameof(UkraineSupportTitle)] = "支持烏克蘭",
        [nameof(UkraineSupportMessage)] = "LightBulb 的作者來自烏克蘭。請考慮支持烏克蘭及其人民。",
        [nameof(LearnMoreButton)] = "了解更多",
        [nameof(UnstableBuildTitle)] = "不穩定版本",
        [nameof(UnstableBuildMessage)] = "您正在使用不穩定的預覽版本，可能包含錯誤。",
        [nameof(SeeReleasesButton)] = "查看發布版本",
        [nameof(LimitedGammaRangeTitle)] = "色彩範圍受限",
        [nameof(LimitedGammaRangeMessage)] = "您的系統限制了可用的色彩範圍，可能影響 LightBulb 的效果。",
        [nameof(FixButton)] = "修正",
        [nameof(WelcomeTitle)] = "歡迎使用 LightBulb",
        [nameof(WelcomeMessage)] = "感謝您使用 LightBulb！請在設定中配置您的位置以開始使用。",
        [nameof(OkButton)] = "確定",
    };
