name: build-portable-only

on:
  workflow_dispatch: # 方便手動點擊執行
  push:
    branches:
      - main # 確保這裡與你 fork 的分支名稱一致
    tags:
      - "*"
  pull_request:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    strategy:
      matrix:
        # 你可以根據需求刪減架構，通常 win-x64 是目前最主流的
        rid: [win-x64, win-x86, win-arm64]
    
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4

      - name: Publish Portable
        # 這裡執行 publish，產出的檔案就是免安裝的資料夾內容
        run: >
          dotnet publish LightBulb
          -p:Version=${{ github.ref_type == 'tag' && github.ref_name || 'custom-build' }}
          -p:CSharpier_Bypass=true
          --output ./publish/${{ matrix.rid }}
          --configuration Release
          --runtime ${{ matrix.rid }}
          --self-contained true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LightBulb-Portable-${{ matrix.rid }}
          path: ./publish/${{ matrix.rid }}
          if-no-files-found: error
